spring:
  flyway:
    enabled: false
  profiles:
    active: dev
    group:
      dev:
        - local-dev
        - debug
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
server:
  error:
    include-message: always
    include-binding-errors: always
springdoc:
  show-actuator: true
management:
  endpoint:
    health:
      show-details: always

education:
  security:
    jwt:
      secret: eitu9aichae7eitee9XiciweishohW3pieshaifasosai5xie9Oomobulohyu8ie
      access-expire-in: 10m
      refresh-expire-in: 3d
      admins:
        someteacher:
          email: admin@gmail.com
          password: $2a$12$9K2iuk7VZ2dUU7srnqUpG.o/sf5oQphQvLvx7JBRQmPT0lQtrgGdy